title: Yang
description: My Personal Blog
author: Yang
logo: http://i1.piimg.com/567571/d96cbfd31ef4efd1.png
github: https://lemon2017.github.io/LemoNade
about: Freelance developer

baseurl: "https://lemon2017.github.io/LemoNade"
url: "https://lemon2017.github.io/LemoNade"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
